// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {peer} from '../models';
import {clents} from '../models';

export function AddGroup(arg1:string):Promise<void>;

export function AddPeer(arg1:peer.Peer):Promise<peer.Peer>;

export function CommunityDistribute(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function DelGroup(arg1:string):Promise<void>;

export function DelPeer(arg1:string):Promise<void>;

export function Depositin(arg1:string,arg2:number,arg3:number,arg4:number,arg5:string,arg6:string):Promise<void>;

export function Depositout(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<void>;

export function EditGroup(arg1:string,arg2:string):Promise<void>;

export function EditPeer(arg1:peer.Peer):Promise<peer.Peer>;

export function GetNewAddress(arg1:string,arg2:string):Promise<void>;

export function GetPeerGroup():Promise<{[key: string]: string}>;

export function GetPeerList():Promise<Array<peer.Peer>>;

export function SendToAddress(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<clents.RespSendToAddress>;

export function SetStatus(arg1:string,arg2:boolean):Promise<void>;

export function VoteIn(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:string,arg9:string):Promise<void>;

export function VoteOut(arg1:string,arg2:number,arg3:string,arg4:number,arg5:number,arg6:number,arg7:string,arg8:string):Promise<void>;
