// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGroup(arg1) {
  return window['go']['peer']['Api']['AddGroup'](arg1);
}

export function AddPeer(arg1) {
  return window['go']['peer']['Api']['AddPeer'](arg1);
}

export function CommunityDistribute(arg1, arg2, arg3, arg4) {
  return window['go']['peer']['Api']['CommunityDistribute'](arg1, arg2, arg3, arg4);
}

export function DelGroup(arg1) {
  return window['go']['peer']['Api']['DelGroup'](arg1);
}

export function DelPeer(arg1) {
  return window['go']['peer']['Api']['DelPeer'](arg1);
}

export function Depositin(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['peer']['Api']['Depositin'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Depositout(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['peer']['Api']['Depositout'](arg1, arg2, arg3, arg4, arg5);
}

export function EditGroup(arg1, arg2) {
  return window['go']['peer']['Api']['EditGroup'](arg1, arg2);
}

export function EditPeer(arg1) {
  return window['go']['peer']['Api']['EditPeer'](arg1);
}

export function GetNewAddress(arg1, arg2) {
  return window['go']['peer']['Api']['GetNewAddress'](arg1, arg2);
}

export function GetPeerGroup() {
  return window['go']['peer']['Api']['GetPeerGroup']();
}

export function GetPeerList() {
  return window['go']['peer']['Api']['GetPeerList']();
}

export function SendToAddress(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['peer']['Api']['SendToAddress'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetStatus(arg1, arg2) {
  return window['go']['peer']['Api']['SetStatus'](arg1, arg2);
}

export function VoteIn(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['peer']['Api']['VoteIn'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function VoteOut(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['peer']['Api']['VoteOut'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
